Package installs cleanly on lbsg.  Still need to test it on zsr.

diff --git a/gutenbach/debian/inst/create-filter-config b/gutenbach/debian/inst/create-filter-config
--- a/gutenbach/debian/inst/create-filter-config
+++ b/gutenbach/debian/inst/create-filter-config
@@ -1,18 +1,32 @@
 #!/bin/sh -e
 
-. /usr/share/debconf/confmodule
-
-if [ ! -d /usr/lib/gutenbach/config ]; then
-    mkdir /usr/lib/gutenbach/config
-fi
-
 echo "Creating /usr/lib/gutenbach/config/gutenbach-filter-config.pl..." >&2
 if [ ! -e "/usr/lib/gutenbach/config/gutenbach-filter-config.pl" ]; then
     touch /usr/lib/gutenbach/config/gutenbach-filter-config.pl
 
-    db_get gutenbach/zephyrclass
-    echo "\$zephyr_class = \"$RET\";" >> /usr/lib/gutenbach/config/gutenbach-filter-config.pl
-    echo "\$hostname = \""`hostname`"\";" >> /usr/lib/gutenbach/config/gutenbach-filter-config.pl
-    db_get gutenbach/printername
-    echo "\$queue = \"$RET\";" >> /usr/lib/gutenbach/config/gutenbach-filter-config.pl
+    failed=
+    if [ -e /usr/lib/gutenbach/config/printername ]; then
+	printername=$(cat /usr/lib/gutenbach/config/printername)
+    else
+	failed="yes"
+    fi
+    if [ -e /usr/lib/gutenbach/config/hostname ]; then
+	hostname=$(cat /usr/lib/gutenbach/config/hostname)
+    else
+	failed="yes"
+    fi
+    if [ -e /usr/lib/gutenbach/config/zephyrclass ]; then
+	zephyrclass=$(cat /usr/lib/gutenbach/config/zephyrclass)
+    else
+	failed="yes"
+    fi
+
+    if [ -z "$failed" ]; then
+	echo "\$zephyr_class = \""$zephyrclass"\";" >> /usr/lib/gutenbach/config/gutenbach-filter-config.pl
+	echo "\$hostname = \""$hostname"\";" >> /usr/lib/gutenbach/config/gutenbach-filter-config.pl
+	echo "\$queue = \""$printername"\";" >> /usr/lib/gutenbach/config/gutenbach-filter-config.pl
+    else
+	echo "Error: One of /usr/lib/gutenbach/config/{printername,hostname,zephyrclass} does not exist!" >&2
+	exit 1
+    fi
 fi
diff --git a/gutenbach/debian/inst/edit-printcap b/gutenbach/debian/inst/edit-printcap
--- a/gutenbach/debian/inst/edit-printcap
+++ b/gutenbach/debian/inst/edit-printcap
@@ -9,18 +9,27 @@ if [ ! -e /etc/lprng/printcap ]; then
     ln -s /etc/printcap /etc/lprng/printcap
 fi
 
-. /usr/share/debconf/confmodule
-db_get gutenbach/printername
+if [ -e /usr/lib/gutenbach/config/printername ]; then
+    printername=$(cat /usr/lib/gutenbach/config/printername)
 
-printcap=$(cat /etc/printcap | grep ^`echo $RET` || true)
-if [ ! -n "$printcap" ]; then
+    printcap=$(cat /etc/printcap | grep ^`echo $printername` || true)
+    if [ ! -n "$printcap" ]; then
     # add the appropriate entry into /etc/printcap, /etc/lprng/printcap
-    echo "$RET" >> /etc/printcap
-    echo "  :server" >> /etc/printcap
-    echo "  :cm=$RET music spooler" >> /etc/printcap
-    echo "  :lp=/dev/null" >> /etc/printcap
-    echo "  :if=|/usr/lib/gutenbach/gutenbach-filter" >> /etc/printcap
-    echo "  :sd=/var/spool/lpd/$RET" >> /etc/printcap
-    echo "  :ml=0:mx=0:sh:sf" >> /etc/printcap
-    echo "  :create_files" >> /etc/printcap
+	echo "$printername" >> /etc/printcap
+	echo "  :server" >> /etc/printcap
+	echo "  :cm=Gutenbach Music Spooler" >> /etc/printcap
+	echo "  :lp=/dev/null" >> /etc/printcap
+	echo "  :if=|/usr/lib/gutenbach/gutenbach-filter" >> /etc/printcap
+	echo "  :lf=/var/spool/lpd/$printername/log" >> /etc/printcap
+	echo "  :sd=/var/spool/lpd/$printername" >> /etc/printcap
+	echo "  :ml=0:mx=0:sh:sf" >> /etc/printcap
+	echo "  :create_files" >> /etc/printcap
+	echo "  :auth_forward=kerberos5" >> /etc/printcap
+	echo "  :use_auth=kerberos5" >> /etc/printcap
+	echo "  :kerberos_id=daemon/"`hostname`".mit.edu@ATHENA.MIT.EDU" >> /etc/printcap
+	echo "  :kerberos_keytab=/etc/daemon.keytab" >> /etc/printcap
+    fi
+else
+    echo "Error: /usr/lib/gutenbach/config/printername does not exist!" >&2
+    exit 1
 fi
diff --git a/gutenbach/debian/inst/run-checkpc b/gutenbach/debian/inst/run-checkpc
--- a/gutenbach/debian/inst/run-checkpc
+++ b/gutenbach/debian/inst/run-checkpc
@@ -13,6 +13,9 @@ fi
 chmod og=rwx /var/spool/lpd
 chmod og=rwx /var/spool/lpd/%P
 
-. /usr/share/debconf/confmodule
-db_get gutenbach/printername
-/usr/sbin/checkpc -P"$RET" -f
+if [ -e /usr/lib/gutenbach/config/printername ]; then
+    printername=$(cat /usr/lib/gutenbach/config/printername)
+    /usr/sbin/checkpc -P"$printername" -f
+else
+    echo "Error: /usr/lib/gutenbach/config/printername does not exist!" >&2
+fi
